//-------- COLIBRA START VARIABLE - DO NOT DELETE NOR add anything before
SET vL.scriptFullNameStart='\\AWWEUQLKPRPS41\d\Projects\GHH_EUCIMBI\3.Include\6.Custom\4.Application\CH\Data-Loader\SQL_DM\3L\MER_3L_TERRITORIES_CH.qvs';



/*
====================================================================== 
	Developer Name: David Vela
	Created:		May-2023
	Purpose:		L (Load) for EULER (euclid swiss fork) 
		            of CH TERRITORIES QVDs:
						* vw_f_terr_current_ch
                        * vw_f_terr_cust
					that we may need for CH apps and store them as QVD files.
                    USING SUBS:
                        * CH_LOAD_EULER_CUST_TER        > LVL3_CH_D_CUST_TERRITORY
                        * CH_LOAD_D_TER_BRICK           > SALESCH/D_TERRITORY and Euler:LVL3_CH_D_TER_BRICK
                        * load_6_core_TER_data::::: 
                        * CH_LOAD_D_TERRITORY_EMP       > 6.Core/LVL3_CH_D_TERRITORY        and Euler/LVL3_CH_D_TERRITORY_EMP_E
* CH_LOAD_D_EMP_TERRITORY       > 6.Core/LVL3_CH_D_EMP_TERRITORY    and Euler/LVL3_CH_D_EMP_TERRITORY
// ======================================================================
*/

SUB CH_LOAD_EULER_CUST_TER(pdrop)        
    D_CUST_TERR_EULER:
        LOAD   
            ter_key & cust_ak                                       AS hcp_ter_key
            ,ter_ak & cust_ak                                       AS hcp_ter_ak
            ,country_code & '-' & cust_mdm_id  & '|' & ter_code     AS "%HCP Territory Key"
            ,country_code & '-' & cust_mdm_id                       AS "%MDM Key"
            ,ter_code                                               AS "%TER Key"
            ,ter_code                                               AS "%Territory BKey"
            ,ter_name                                               AS "Customer Territory Name"
            //,ter_desc                                             AS "Customer Territory"
            ,if(IsNull(ter_desc),ter_name , ter_desc )              AS "Customer Territory"
            ,ter_desc                                               AS "Customer Territory Description"
            ,country_code                                           AS "Customer Country"
            ,emp_name                                               AS "Customer Employee"
            ,emp_id
            ,emp_department
            //,ter_trgt                                             as "Customer Target"
            //,ter_trgt_flag                                        as "Customer Target Flag"
            ,If(IsNull(ter_trgt), 'NT', ter_trgt)                   AS "Customer Target"
            ,If(IsNull(ter_trgt_flag), 0, ter_trgt_flag)            AS "Customer Target Flag"
            ,ter_trgt_cc                                            AS "Customer Target Country Code"
            ,'OVERALL_PRIORITY'                                     AS "Territory Target Type"
            ,country_code                                           AS "%Country Key"
            ,cust_type
            //,DB fields
            ,ter_key                                                AS ter_key
            ,emp_mng_name
            ,cust_mdm_id
            ,ter_name                                               AS tc_name
            ,ter_code                                               AS tc_code
            ,ter_desc                                               AS tc_desc
            ,emp_name
            ,cust_surname
            ,cust_ak
            //--ter_ak, cust_ak, emp_ak,   ter_desc,  cust_firstname,  
            ,sls_team_code
            ,sls_team_name, sls_team_lvl1_name, sls_team_lvl2_name, sls_team_lvl3_name, sls_team_lvl4_name,
            ter_type, ter_rltn_type, effctv_dt, exprtn_dt, cust_main_specialty_name_global, cust_2nd_specialty_name_global, cust_prmry_addr_zip_code,
            country_code                                            AS tc_cc
        FROM "$(vStorePath)/vw_f_terr_cust.qvd"(qvd);
        LEFT JOIN
        LOAD
            ter_key 
            ,'CH-00000'					            AS "Customer Corporation"
            ,ter_lvl3_name  			            AS "Customer Business Unit"
            ,ter_lvl2_name  				        AS "Customer Area"
            ,ter_lvl1_name					        AS "Customer District"
            ,ter_lvl2_code
            ,ter_lvl3_code
        FROM "$(vStorePath)vw_f_terr_current_ch.qvd"(qvd);
        LEFT JOIN
        LOAD
            ter_ak & cust_ak               AS hcp_ter_ak
            ,calculated_overall_priority
        FROM "$(vStorePath)vw_f_terr_cust_calc_overall_priority.qvd"(qvd);


        STORE D_CUST_TERR_EULER INTO [Lib://$(vG.COREVersionLoadPathData)/LVL3_$(v.Region)_D_HCP_TERRITORY_E.qvd](qvd);
        STORE D_CUST_TERR_EULER INTO [$(vStorePath)/LVL3_$(v.Region)_D_CUST_TERRITORY.qvd](qvd);
        DROP TABLE D_CUST_TERR_EULER;
END SUB; 

SUB CH_LOAD_D_TER_BRICK(ov)
    // todo: move logic from LEVEL_3_CH_TERRITORY > D_TERRITORY >  LVL3_CH_D_TERRITORY.qvd TO euler 
    /* QVD OBS : in 
        bidm: 3.Load/4.CustomerEngagementCore\LEVEL_3_CH_D_EMP_TERR.qvs'; 
            BU_EMPLOYEE > "lib://$(vG.CH_GeneralLoadPath)/D_BU_EMPLOYEE.qvd"(qvd);  > vw_d_employee_territory
            TERRITORY   > "lib://$(vG.CH_GeneralLoadPath)/D_TERRITORY.qvd"(qvd);    > vw_d_territory_ch (xlsx needed)
        cim: \6.CORE\CH\CH_v1.1_20211001\LEVEL_3_CH_TERRITORY.qvs 
        load: 

    D_TERRITORY:
    LOAD * 
        FROM [lib://GHH_EUCIMBI_DATA_SALESCH_SS/2.QVD/3.Load/D_TERRITORY.qvd](qvd)
        // created : in 3.Load/4.CustomerEngagementCore\LEVEL_3_CH_D_EMP_TERR.qvs'
    ;    
    */
    TERRITORY:
        LOAD  //distinct
            "ter_code"                          as  "%TER Key"
            ,ter_code                           as "Territory Code"
            ,'Y'                                as "Territory Brick Active Flag"
            ,b_region_key                       as %Brick
            ,b_region_key                       as %RegionKey
            ,AutoNumber('B' & b_region_key)     as %RegionKeyAuto
            ,replace("ter_code",'CH_','')       as TerritoryName
            //"%Territory Key"  as TK,
            //"Territory Source ID" as TSID,//"%Territory Key"        
            //'B' & RIGHT("Territory Brick Code", 4) as %RegionKey,
            ,bri_desc_vva                       as RegionName
            ,bri_desc_vva                       as geo_brick_name //BERNJOAO 20220202 - Testing KML Geo Mapping
        //FROM [lib://$(vG.COREVersionTransformPathData)/LVL2_f_territory_brick.qvd](qvd)where "Dm Area Code" = 'CH' and "Territory Brick Active Flag" = 'Y'
        FROM "$(vStorePath)vw_f_terr_bricks.qvd"(qvd)
            WHERE   wildmatch(ter_code,'CH_*') and  "%Country Key" = 'CH'
        ;        ;
        join(TERRITORY)
        LOAD
            BrickID as %Brick, 
            BrickID &' '&BrickName as  BrickName,
            RegionShort as %CantonKey,
            RegionName as CantonName,
            Bezirk
            FROM [lib://$(vG.ImportPath)/$(vCountry)/CH_Geo.xlsx](ooxml, embedded labels, table is BrickRegions)
    ;
    /* TODO bugfix > 1 canton can belong to multiple bricks. 
    */ 


    if ov = 1 Then      
        STORE TERRITORY INTO "lib://$(vG.CH_GeneralLoadPath)/D_TERRITORY.qvd"(qvd);
    End if; 
    //STORE TERRITORY INTO [$(vStorePath)/LVL3_CH_D_TERRITORY.qvd](qvd);    // not to be mix with D_TERRITORY
    STORE TERRITORY INTO [$(vStorePath)/LVL3_CH_D_TER_BRICK.qvd](qvd);
    DROP TABLE TERRITORY;
END SUB; 
//CALL CH_LOAD_D_TER_BRICK(1);
//.
SUB load_6_core_TER_data
  D_TER: 
    LOAD
        Corporate,
        "Business Unit",
        Area,
        District,
        Territory,
        "Territory Parent",
        "Territory Path",
        "%Territory BKey",
        "%Territory BKey Parent",
        "Territory Description",
        "Territory Country Code",
        "%TER Key",
        "Employee Name",
        "%Employee BKey",
        Level
    FROM [lib://GHH_EUCIMBI_DATA_ALL_SS/2.QVD/3.Load/6.CORE/CH/to_be_decomission/LVL3_CH_D_TERRITORY.qvd](qvd)
  ;

  EMP_TER:
    LOAD
        "%Employee BKey",
        "%Country Key",
        "%Territory BKey",
        "%Employee Key",
        "Employee Country Code",
        "Employee First Name",
        "Employee Surname",
        "Employee Name",
        "Employee Email",
        "Employee Alias",
        "Employee Active Flag",
        "Employee Division",
        "Employee Department",
        "Employee Title",
        "Employee Win Number",
        "Employee Primary Territory",
        "%Sales Team Key",
        "Employee Sales Line",
        "Employee Business Unit",
        "Employee Manager ID",
        "Employee Manager Name",
        "Employee Profile Name",
        "Employee Data Access Flag",
        "%Territory Key",
        "OM Corporate",
        "OM Business Unit",
        "OM Area",
        "OM District",
        "OM Territory",
        "Territory Name",
        "%TER Key"
    FROM [lib://GHH_EUCIMBI_DATA_ALL_SS/2.QVD/3.Load/6.CORE/CH/to_be_decomission/LVL3_CH_D_EMP_TERRITORY.qvd](qvd)
  ;
  // testing: 
   BU_EMPLOYEE:
            LOAD
                "%Employee BKey"AS             "%Employee BKey",
                "%Country Key"AS                "%Country Key2",
                "%Territory BKey"AS             "%Territory BKey2",
                "%Employee Key"AS               "%Employee Key2",
                "Employee Country Code"AS       "Employee Country Code2",
                "Employee First Name"AS         "Employee First Name2",
                "Employee Surname"AS            "Employee Surname2",
                "Employee Name"AS               "Employee Name2",
                "Employee Email"AS              "Employee Email2",
                "Employee Alias"AS              "Employee Alias2",
                "Employee Active Flag"AS        "Employee Active Flag2",
                "Employee Division"AS           "Employee Division2",
                "Employee Department"AS         "Employee Department2",
                "Employee Title"AS              "Employee Title2",
                "Employee Win Number"AS         "Employee Win Number2",
                "Employee Primary Territory"AS  "Employee Primary Territory2",
                "%Sales Team Key"AS             "%Sales Team Key2",
                "Employee Sales Line"AS         "Employee Sales Line2",
                "Employee Business Unit"AS      "Employee Business Unit2",
                "Employee Manager ID"AS         "Employee Manager ID2",
                "Employee Manager Name"AS       "Employee Manager Name2",
                "Employee Profile Name"AS        "Employee Profile Name2",
                "Employee Data Access Flag"AS   "Employee Data Access Flag2",
                "%Territory Key"AS              "%Territory Key2",
                "OM Corporate"AS                "OM Corporate2",
                "OM Business Unit"AS            "OM Business Unit2",
                "OM Area"AS                     "OM Area2",
                "OM District"AS                 "OM District2",
                "OM Territory"AS                "OM Territory2",
                "Territory Name"AS              "Territory Name2",
                "%TER Key" AS                   "%TER Key2"
            FROM [lib://GHH_EUCIMBI_DATA_ALL_SS/2.QVD/3.Load/6.CORE/CH/to_be_decomission/LVL3_CH_D_EMP_TERRITORY.qvd](qvd);
END SUB;
//CALL load_6_core_TER_data; 
SUB CH_LOAD_D_EMP_TERRITORY(ov)
    /* BU_EMPLOYEE > "lib://$(vG.CH_GeneralLoadPath)/D_BU_EMPLOYEE.qvd"(qvd);  > vw_d_employee_territory
    */
    if ov = 999 then
        BU_EMPLOYEE:
            LOAD
                "%Employee BKey",
                "%Country Key",
                "%Territory BKey",
                "%Employee Key",
                "Employee Country Code",
                "Employee First Name",
                "Employee Surname",
                "Employee Name",
                "Employee Email",
                "Employee Alias",
                "Employee Active Flag",
                "Employee Division",
                "Employee Department",
                "Employee Title",
                "Employee Win Number",
                "Employee Primary Territory",
                "%Sales Team Key",
                "Employee Sales Line",
                "Employee Business Unit",
                "Employee Manager ID",
                "Employee Manager Name",
                "Employee Profile Name",
                "Employee Data Access Flag",
                "%Territory Key",
                "OM Corporate",
                "OM Business Unit",
                "OM Area",
                "OM District",
                "OM Territory",
                "Territory Name",
                "%TER Key"
            FROM [lib://GHH_EUCIMBI_DATA_ALL_SS/2.QVD/3.Load/6.CORE/CH/to_be_decomission/LVL3_CH_D_EMP_TERRITORY.qvd](qvd)
            //FROM [lib://$(vG.CH_COREGeneralLoadPathData)/LVL3_CH_D_EMP_TERRITORY.qvd](qvd)
            //FROM "$(vStorePath)vw_d_employee_territory.qvd"(qvd)
            //FROM [$(vStorePathM)vw_f_terr_emp.qvd](qvd)
        ; 
    else  // euler T: 
        /* fixes:  
            * Employee Business Unit  BU without the "CH DIRECTOR" text
            * %Sales Team Key ok >> MER_3L_TERRITORIES. 
        */ 
        BU_EMPLOYEE:
            LOAD DISTINCT
                "%Employee BKey",
                "%Country Key",
                "%Territory BKey",
                "%Employee Key",
                "Employee Country Code",
                "Employee First Name",
                "Employee Surname",
                "Employee Name",
                "Employee Email",
                "Employee Alias",
                "Employee Active Flag",
                "Employee Division",
                "Employee Department",
                "Employee Title",
                "Employee Win Number",
                "Employee Primary Territory",
                "%Sales Team Key",                  // wrong = same as sales line
                "Employee Sales Line",
                //"Employee Business Unit",         // wrong <<< sls_team_code
                //"Employee Sales Line" as "Employee Business Unit",   // wrong 
                "Employee Manager ID",
                "Employee Manager Name",
                "Employee Profile Name",
                "Employee Data Access Flag",
                "%Territory Key",
                "%TER Key", 
                "Territory Name",
                // Hierarchy: 
                "OM Corporate"                                         as "OM Corporate",
                "OM Corporate"                                         as om_corp_code,
                //"OM Business Unit"
                "OM Business Unit"                                     as om_bu,
                //"OM Area",
                "OM Area"                                              as om_area,
                //"OM District", // MISSING 
                ''  AS  "OM District",
                //"OM Territory",   // MISSING
                //if(IsNull(ter_desc),ter_name , ter_desc )            as "OM Territory",
                if(IsNull(ter_desc),ter_name , ter_desc )              as "OM Territory",
                ter_key
            //  FROM [lib://GHH_EUCIMBI_DATA_ALL_SS/2.QVD/3.Load/6.CORE/CH/to_be_decomission/LVL3_CH_D_EMP_TERRITORY.qvd](qvd)
            //FROM [$(vStorePathM)vw_f_terr_emp.qvd](qvd)
            FROM [lib://$(vG.EulerVersionLoadPathData)LVL3_MER_D_EMP_TERRITORY.qvd](qvd)
            where  "%Country Key" = 'CH'
            ;  
            Left Join(BU_EMPLOYEE)
                Load distinct   ter_lvl3_code           as  om_bu
                                ,ter_lvl3_desc	        as  "OM Business Unit"  
                                //,ter_lvl3_name	        as  "Employee Business Unit"   // wrong
                                ,replace(ter_lvl3_name, ' DIRECTOR', '')	        as  "Employee Business Unit"   // quick fix: 
                FROM "$(vStorePathM)vw_f_terr_current_e.qvd"(qvd)
            ;  
            Left Join(BU_EMPLOYEE)
                Load distinct   ter_lvl2_code           as  om_area
                                ,ter_lvl2_desc	        as  "OM Area"  
                FROM "$(vStorePathM)vw_f_terr_current_e.qvd"(qvd)
            ;
    end if; 
    if ov = 1 Then       
        STORE BU_EMPLOYEE INTO "Lib://$(vG.COREVersionLoadPathData)/LVL3_CH_D_EMP_TERRITORY.qvd"(qvd);           
    End if; 
    STORE BU_EMPLOYEE INTO "Lib://$(vG.COREVersionLoadPathData)/LVL3_CH_D_EMP_TERRITORY_E.qvd"(qvd);   
    STORE BU_EMPLOYEE INTO [$(vStorePath)/LVL3_CH_D_EMP_TERRITORY_E.qvd](qvd);       
    DROP TABLE BU_EMPLOYEE;
END SUB; 
//CALL CH_LOAD_D_EMP_TERRITORY(1);
SUB CH_LOAD_D_TERRITORY_EMP(ov)
    //LVL3_CH_D_TERRITORY >> To be generated in EULER
    //3.Load\6.CORE\CH\CH_v1.1_20211001\LEVEL_3_CH_TERRITORY.qvs';
    if ov = 999 then  
            D_TER_EMP: 
                LOAD
                    Corporate,
                    "Business Unit",
                    Area,
                    District,
                    Territory,
                    "Territory Parent",
                    "Territory Path",
                    "%Territory BKey",
                    "%Territory BKey Parent",
                    "Territory Description",
                    "Territory Country Code",
                    "%TER Key",
                    "Employee Name",
                    "%Employee BKey",
                    Level
                FROM [lib://GHH_EUCIMBI_DATA_ALL_SS/2.QVD/3.Load/6.CORE/CH/to_be_decomission/LVL3_CH_D_TERRITORY.qvd](qvd)
            ;
    elseif ov = 998 then    // euler T: 
            D_TER_EMP:
            LOAD DISTINCT
                     // Hierarchy: 
                    "OM Corporate"                                 as Corporate,
                    "OM Corporate"                                 as om_corp_code,
                    "OM Business Unit"                             as "Business Unit",
                    "OM Business Unit"                             as om_bu,
                    "OM Area"                                      as Area,
                    "OM Area"                                      as om_area,
                    "OM District"                                  as District, // MISSING 
                    ''                                             as "OM District",
                    if(IsNull(ter_desc),ter_name , ter_desc )      as "Territory",
                    ter_key,
                    ''                                             as  "Territory Parent",
                    ''                                             as  "Territory Path",
                    "%Territory BKey",
                    ''                                             as "%Territory BKey Parent",
                    ter_desc                                       as "Territory Description",
                    "%Country Key"                                 as "Territory Country Code",
                    ter_code                                       as "%TER Key",
                    1                                              as Level,
                    // employee: 
                    "%Employee BKey",
                    "Employee Name",
                    "%Country Key"
            FROM [lib://$(vG.EulerVersionLoadPathData)LVL3_MER_D_EMP_TERRITORY.qvd](qvd)
            where  "%Country Key" = 'CH'
            ; 
    else  
            D_TER_EMP:
            LOAD
                territory_bkey          as "%Territory BKey"
                ,territory_bkey         as "%TER Key"
                ,corporate              as Corporate
                ,business_unit          as "Business Unit"
                ,area                   as "Area"
                ,district               as "District"
                ,territory              as "Territory"
                ,territory_bkey_parent  as "%Territory BKey Parent"
                ,territory_parent       as "Territory Parent"
                ,territory_path         as "Territory Path"
                ,territory_description  as "Territory Description"
                ,country_code           as "Territory Country Code"
                ,employee_bkey          as "%Employee BKey"
                ,employee_name          as "Employee Name"
                ,level                  as "Level"
                ,country_code           as "%Country Key"
            FROM [Lib://$(vG.EulerMarketVersionLoadPathData)vw_v_f_terr_emp_ql3.qvd](qvd)
            ;
        End if; 
    if ov = 1 Then       
        STORE D_TER_EMP INTO "Lib://$(vG.COREVersionLoadPathData)/LVL3_CH_D_TERRITORY.qvd"(qvd);           
    End if; 
    STORE D_TER_EMP INTO [Lib://$(vG.COREVersionLoadPathData)/LVL3_CH_D_TERRITORY_EMP_E.qvd](qvd);    
    STORE D_TER_EMP INTO [$(vStorePath)/LVL3_CH_D_TERRITORY_EMP_E.qvd](qvd);
    DROP TABLE D_TER_EMP;
END SUB; 
//CALL CH_LOAD_D_TERRITORY_EMP(1);

//-------- COLIBRA END VARIABLE - DO NOT DELETE NOR add anything after
SET vL.scriptFullNameEnd='\\AWWEUQLKPRPS41\d\Projects\GHH_EUCIMBI\3.Include\6.Custom\4.Application\CH\Data-Loader\SQL_DM\3L\MER_3L_TERRITORIES_CH.qvs';