// asdf
TEST:
load
    CustomerName
from [lib://somepath/customer.qvs](qvs)
;

// asdf
TEST:
load
    CustomerName
from [lib://somepath/customer.qvs](qvs)
;


SET vText = 'asdfasdf to lore ipsum blabla from do not mark me as select';

SUB SET_TOOLSTIPS

    /* asdf */
    LOAD
        '$(vText)' as "ToolTip"
    INLINE [
        ToolTip
        '$(vText)'
    ];
    
    LOAD
        '$(vText)' as "ToolTip2"
    INLINE [
        ToolTip2
        '$(vText)'
    ];
    
    LOAD
        '$(vText)' as "ToolTip3"
    INLINE [
        ToolTip3
        '$(vText)'
    ];
    
END SUB;

DROP TABLE TABLE1, TABLE2, TABLE3;
